
# This file is generated via the `serve` command.
# Changes made to this file might be overwritten.
# A full list of configurations are available here: https://supabase.com/docs/guides/functions/unit-test

project_id = "lvmsynntdryfhoyqdwch"

[functions.sync-products]
verify_jwt = false

[functions.sync-orders]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.restart]
verify_jwt = true
