// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvmsynntdryfhoyqdwch.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2bXN5bm50ZHJ5ZmhveXFkd2NoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2Njg1NDcsImV4cCI6MjA2MTI0NDU0N30.LADKRy9_qASg6uMwt0dx1qad8VlPOc_vFl75XwglUiA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);